//Expressions Watch Window Variables for Lab 3 (Open Loop PCMC)
expRemoveAll()
//Variables
expAdd ("BUCK_labNumber",getNatural())
expAdd ("BUCK_dacSetRef_pu",getNatural())
expAdd ("BUCK_dacSet_pu",getNatural())
expAdd ("BUCK_vInSensed_Volts",getNatural())
expAdd ("BUCK_vOutSensed_Volts",getNatural())
expAdd ("BUCK_iOutSensed_Amps",getNatural())
expAdd ("BUCK_iOutTripSetRef_Amps",getNatural())
expAdd ("BUCK_iOutTripFlag",getNatural())
expAdd ("BUCK_iOutTripFlagClear",getNatural())
expAdd ("BUCK_activeLoadEnable", getNatural())
expAdd ("BUCK_activeLoadContEnable",getNatural())
expAdd ("BUCK_vOutLogRef",getNatural())
